version: '3.10'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: wk9_trade_crypto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Musy19
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  airflow-init:
    image: apache/airflow:2.5.0
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    entrypoint: /bin/bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.5.0
    depends_on:
      - airflow-init
      - airflow-postgres
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: "/opt/airflow/dags:/home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps"
    command: webserver
    volumes:
      - /home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps/airflow/dags:/opt/airflow/dags
      - /home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps:/home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps

  airflow-scheduler:
    image: apache/airflow:2.5.0
    depends_on:
      - airflow-init
      - airflow-postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: "/opt/airflow/dags:/home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps"
    command: scheduler
    volumes:
      - /home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps/airflow/dags:/opt/airflow/dags
      - /home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps:/home/moraa/Documents/10_academy/Week-9/Crypto-Trading-Engineering/MLOps

  airflow-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  airflow_pgdata:
