version: '3.10'

services:
  postgres:
    image: postgres:latest
    container_name: wk9_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - mlops_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_auth.sql:/docker-entrypoint-initdb.d/init_auth.sql

volumes:
  mlops_pgdata:
    external: true
