"""Add data_path, fromdate, todate, cash, strategies to Scene

Revision ID: 3884f1d9ab69
Revises: e6d78ee05f99
Create Date: 2024-06-28 05:35:44.499799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3884f1d9ab69'
down_revision = 'e6d78ee05f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('fromdate', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('todate', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('cash', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('strategies', sa.JSON(), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('parameters')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('strategies')
        batch_op.drop_column('cash')
        batch_op.drop_column('todate')
        batch_op.drop_column('fromdate')
        batch_op.drop_column('data_path')

    # ### end Alembic commands ###
